### PR TITLE
'@esri/react-arcgis' instead of 'react-arcgis'

### PR DESCRIPTION
**Pull request by abdel-abdelrazek**

### CODE REVIEW

**Comment by jgravois** [comment]
great catch!

**Comment by jgravois** [comment]
looks like you have a merge conflict to resolve though.

**Comment by tomwayson** [comment]
This can be merged now, right?

Also, I don't have a merge button. 🤔

**Comment by abdel-abdelrazek** [comment]
After my update there were conflicts, i fixed them.
As shown in attached pic the first three i did them myself and no issues with them.
But the 4th one, i'm not sure how this
Capture
 merge has been done.

**Comment by jgravois** [comment]
@tomwayson done (and done).

**Pull request merged**
