### PR TITLE
update js api to 4.12

### PR DESCRIPTION
**Pull request by gavinr**
addresses #86

### CODE REVIEW

**Comment by tomwayson** [comment]
Thanks @gavinr, but I won't release this w/o first making [esri-loader a peerDependencey](https://github.com/Esri/react-arcgis/issues/86#issuecomment-481055198).

**Comment by gavinr** [comment]
Since there hasn't been a PR for setting esri-loader as a peerDependency for 3 months, I was thinking we could/should update to the latest JS api and esri-loader now ([there is precedence for this](https://github.com/Esri/react-arcgis/commit/563237f5dcf8ceaf0e30a02e818c01e39da4f574#diff-b9cfc7f2cdf78a7f4b91a753d10865a2R9)), and then add in the peer dependency thing as someone has time in the future. .... is there a down-side to this plan I'm missing?

**Comment by tomwayson** [comment]
Yeah, the downside is the cost of continues maintenance.

**Comment by tomwayson** [comment]
Hm... the diff you linked to above got me thinking.

First, I think the ArcGIS types need to moved to a dev dep, right?

Second, react and react-dom should also be peer deps too - [this is the recommended best practice for libraries like this that essentially act as a react plugin](https://yarnpkg.com/blog/2018/04/18/dependencies-done-right/).

Moving to peer deps is going to be a breaking change and require a major version bump, so we should do them all at once.

**Comment by changezshaikh27** [comment]
Hi guys, any updates on when this PR gets merged?

**Comment by tomwayson** [comment]
I don't think it should be merged for the reasons I enumerated above.

Until we make esri-loader a peer dependency, you can always pass the JSAPI version in `loaderOptions`.

**Pull request closed without merging**
