### PR TITLE
chore: upgrade development environment

### PR DESCRIPTION
**Pull request by Favna**
Note: This also covers #100 and will close that PR when this is merged. This is a step on top of #100. It is recommended to merge this PR but if you guys don't want all these changes feel free to deny this and only merge #100.

As for where this PR diverts from #100: 

- Upgrade all devDependencies (07518fa9008622357c45f17869b096b7e9f6db2f) & (190e43cc3269232558d733621a871fa0221f3466)
- Upgrade all regular dependencies (07518fa9008622357c45f17869b096b7e9f6db2f)
- Include missing types definitions to devDependencies (7ebafc4194b9400981b1f51a97ecd69136ab5282)
- Enabled full strict mode for TypeScript and resolved some issues
caused by it (such as adding index signatures to some types) (07518fa9008622357c45f17869b096b7e9f6db2f)
- Removed the "no-use-before-declare" TSLint rule as it has been
deprecated since TS 2.9 in favor of the compiler option (07518fa9008622357c45f17869b096b7e9f6db2f)
- Added a `lint` npm script and ran it with the `--fix` option to run TSLint autofix (e7888837f2c2cb5675880f8684f7262fd343d703)
- Added a `test:all` npm script to run sequentially `test`, `test:junit`, `report:cobertura` and `report:lcov` (07518fa9008622357c45f17869b096b7e9f6db2f)

Upgrading of `nyc` also fixes security vulnerabilities. Previously audit showed the following, caused by a prototype pollution in lodash, a dependency of nyc. You can read more about this security vulnerability [here, on the snyk blog](https://snyk.io/blog/snyk-research-team-discovers-severe-prototype-pollution-security-vulnerabilities-affecting-all-versions-of-lodash/)

```sh
$ npm audit
                                                                                
                       === npm audit security report ===                        
                                                                                
# Run  npm install --save-dev nyc@14.1.1  to resolve 2 vulnerabilities
SEMVER WARNING: Recommended action is a potentially breaking change
┌───────────────┬──────────────────────────────────────────────────────────────┐
│ High          │ Prototype Pollution                                          │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Package       │ handlebars                                                   │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Dependency of │ nyc [dev]                                                    │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Path          │ nyc > istanbul-reports > handlebars                          │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ More info     │ https://npmjs.com/advisories/755                             │
└───────────────┴──────────────────────────────────────────────────────────────┘


┌───────────────┬──────────────────────────────────────────────────────────────┐
│ High          │ Prototype Pollution                                          │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Package       │ lodash                                                       │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Dependency of │ nyc [dev]                                                    │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Path          │ nyc > istanbul-reports > handlebars > async > lodash         │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ More info     │ https://npmjs.com/advisories/1065                            │
└───────────────┴──────────────────────────────────────────────────────────────┘


found 2 high severity vulnerabilities in 7930 scanned packages
  2 vulnerabilities require semver-major dependency updates.
```

---

Content from #100 copied over:

Primarily I moved react to peerDependencies so users can install their own version of React 16, rather potentially getting multiple versions of React loaded. 

As an aside I also noticed you were publishing the source directory. There should never be a need for this assuming every source file gets bundled into dist - and even if source files would be needed they could only ever be used by other tsx users as (thankfully, btw) the source is written in tsx. Admittedly webpack would ensure these files don't actually get included in the final bundle anyway, but it doesn't eye very nice to see "src" here: 

image

### CODE REVIEW

**Comment by tomwayson** [comment]
I'm inclined to go w/ this PR over #100 

I'm going to pull and run it locally.

It'd be good if a more TypeScripty person like @gavinr would be willing to review as well.

**Comment by Favna** [comment]
@tomwayson thanks for the review! Did another dev dependencies bump as there were quite a few again, as well as bumping esri-loader from 2.10.0 to 2.10.1. 

As an aside, you guys might want to look into a service such as (the 100% free) Dependabot (https://dependabot.com/). It's a bot, now owned and managed by GitHub itself, to automatically bump versions. It can be configured to do so on your own intervals (day, week, etc)

**Comment by Favna** [comment]
@gavinr great feedback, I've addressed all the points made except for the loaderOptions, which I prepped locally. Before I push that one however I have 1 question. I can see `version` and `css` as props for `loaderOptions`, but are there any others, where might they be documented? While at it I'm also making it a properly typed object rather than just having it typed as `Object`. Added some TSDoc as well:
image


```ts
export interface MapLoaderOptions {
    /** The version of the Arcgis JS API to load */
    version: string;
    /** Whether to also load the Arcgis stylesheet */
    css: boolean;
}
```

**Comment by tomwayson** [comment]
@Favna 

You should be able to use esri-loader's `ILoadScriptOptions`:

https://github.com/Esri/esri-loader/blob/946a87a52ab0c966ff22b921a2267ad4fd792fd6/src/script.ts#L50-L56

Unfortunately esri-loader's APIs do not yet have TSDoc comments.

**Comment by Favna** [comment]
And that's the last bit covered in d9e311e302dcaaea99e92331138415f4f4c1be92. Imported the mentioned interface for the typings, the only proper way to do it really.

**Comment by nicksenger** [comment]
@Favna awesome work on this! Overall the changes look really good, however I had to add `"skipLibCheck": true` to tsconfig in order to avoid this error when building the project:

```
node_modules/@types/react/index.d.ts:107:31 - error TS2344: Type 'T' does not satisfy the constraint 'string | ((props: any) => ReactElement<any, string | ... | (new (props: any) => Component<any, any, any>)> | null) | (new (props: any) => Component<any, any, any>)'.
  Type 'string | number | ((props: any) => ReactElement<any, string | ... | (new (props: any) => Component<any, any, any>)> | null) | (new (props: any) => Component<any, any, any>)' is not assignable to type 'string | ((props: any) => ReactElement<any, string | ... | (new (props: any) => Component<any, any, any>)> | null) | (new (props: any) => Component<any, any, any>)'.
    Type 'number' is not assignable to type 'string | ((props: any) => ReactElement<any, string | ... | (new (props: any) => Component<any, any, any>)> | null) | (new (props: any) => Component<any, any, any>)'.
      Type 'T' is not assignable to type 'string'.
        Type 'string | number | ((props: any) => ReactElement<any, string | ... | (new (props: any) => Component<any, any, any>)> | null) | (new (props: any) => Component<any, any, any>)' is not assignable to type 'string'.
          Type 'number' is not assignable to type 'string'.

107     > extends ReactElement<P, T> { }
```

I tried bumping & downgrading various dependencies but wasn't able to track down what's causing it exactly. I haven't been working with TS much lately, so it could be something obvious that I've overlooked. Did anyone else experience this issue?

This isn't directly related, but it looks like running the build script is not part of the TravisCI config. It may be a good idea to have it in there.

**Comment by Favna** [comment]
@nicksenger can you share the exact code where you get this? I just tried to run `npm run build` in the project and everything compiles just fine.

There are also no occurrences of `string | number  ` in react-arcgis, are you sure the error comes from this library?

When running `build` on my machine:
```sh
$ npm run build

> @esri/react-arcgis@4.0.0 build /Users/favna/dev/react-arcgis
> run-s build:types build:scripts


> @esri/react-arcgis@4.0.0 build:types /Users/favna/dev/react-arcgis
> tsc


> @esri/react-arcgis@4.0.0 build:scripts /Users/favna/dev/react-arcgis
> webpack -p

ℹ ｢atl｣: Using typescript@3.6.3 from typescript
ℹ ｢atl｣: Using tsconfig.json from /Users/favna/dev/react-arcgis/tsconfig.json
ℹ ｢atl｣: Checking started in a separate process...
ℹ ｢atl｣: Time: 33ms
Hash: fecb9b8f2178565816b8
Version: webpack 4.41.0
Time: 2693ms
Built at: 10/01/2019 9:46:46 AM
                               Asset       Size  Chunks                   Chunk Names
      ../esm/components/ArcBase.d.ts   1.84 KiB          [emitted]        
../esm/components/ArcComposites.d.ts   1.01 KiB          [emitted]        
 ../esm/components/ArcContainer.d.ts  428 bytes          [emitted]        
../esm/components/MapComposites.d.ts  513 bytes          [emitted]        
../esm/components/WebComposites.d.ts  559 bytes          [emitted]        
                   ../esm/index.d.ts  933 bytes          [emitted]        
                            index.js   9.75 KiB       0  [emitted]        index
                        index.js.map   38.9 KiB       0  [emitted] [dev]  index
Entrypoint index = index.js index.js.map
[0] external {"root":"React","commonjs2":"react","commonjs":"react","amd":"react"} 42 bytes {0} [built]
[2] multi ./src/ts/index.ts 28 bytes {0} [built]
[3] ./src/ts/index.ts + 5 modules 11.6 KiB {0} [built]
    | ./src/ts/index.ts 584 bytes [built]
    |     + 5 hidden modules
    + 1 hidden module
```

Some system information for comparison sake:

- OS: MacOS Mojave version 10.14.6 (and same result on my Windows 10 machine at home)
- NodeJS: version 12.10.0
  - If you're running a version < 10 then upgrade now, 10 is currently LTS and 8 is maintenance LTS and not recommended. At the end of october (it's the 1st today!) 12 will become active LTS. [NodeJS Release Schedule here](https://github.com/nodejs/Release#release-schedule)
- TypeScript version: 3.6.3 (also locally installed in DevDependencies of this lib)

**Comment by nicksenger** [comment]
@Favna it looks like Travis CI was able to build everything from this PR just fine:

- [branch](https://travis-ci.org/Esri/react-arcgis/builds/592041762?utm_source=github_status&utm_medium=notification) (your changes + running build in CI)
- [build log](https://travis-ci.org/Esri/react-arcgis/builds/592041762?utm_source=github_status&utm_medium=notification)

So I'm guessing the issue is something specific to my configuration ‾\_(ツ)_/‾

**Pull request merged**
