### PR TITLE
add a demo app

### PR DESCRIPTION
**Pull request by jgravois**
i thought a quickstart would be helpful for other newbs like me...

### CODE REVIEW

**Comment by nicksenger** [comment]
@jgravois this looks great. Thanks for updating the type definitions and adding the yarn lock as well!

**Comment by jgravois** [comment]
awesome. I don't have :key:s to merge this yet, but I'd like to wait for the PR below to land first anyway.

https://github.com/Esri/esri-loader/pull/143

**Comment by telkandrew** [comment]
Able to get the NYC FeatureLayer running in your demo app, thanks @jgravois. For whatever reason it looks like the issue is with our own FeatureLayer, closing the issue.

**Comment by jgravois** [comment]
glad to hear you tracked down the problem @telkandrew. thanks for taking the time to let us know. ⛵️ 	

@nicksenger, 2e09681 has a little more housekeeping. i'll merge as soon as the 4.10 typings are actually available if everything looks good to you.

**Pull request merged**
